apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: heartbeat
spec:
  type: heartbeat
  version: 7.16.0
  elasticsearchRef:
    name: elasticsearch-sample
  config:
    heartbeat.monitors:
    - type: tcp
      schedule: '@every 5s'
      hosts: ["elasticsearch-sample-es-http.elk.svc:9200"]
    - type: tcp
      schedule: '@every 5s'
      hosts: ["kibana-sample-kb-http.elk.svc:5601"]
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0