# This sample sets up a an Elasticsearch cluster along with a Kibana instance
# and an APM server, configured to be able to communicate with each other
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-$ECK_DEPLOYMENT_NAME
spec:
  version: $ELASTIC
  http:
    service:
      spec:
        type: NodePort
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    count: 1
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            securityContext:
              privileged: true
            resources:
              limits:
                memory: 2Gi  
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-$ECK_DEPLOYMENT_NAME
spec:
  version: $ELASTIC
  count: 1
  elasticsearchRef:
    name: "elasticsearch-$ECK_DEPLOYMENT_NAME"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-$ECK_DEPLOYMENT_NAME
spec:
  version: $ELASTIC
  http:
    service:
      spec:
        type: NodePort
  count: 1
  elasticsearchRef:
    name: "elasticsearch-$ECK_DEPLOYMENT_NAME"
  
